name: Build STM32 Project

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache STM32CubeIDE build
        uses: actions/cache@v4
        with:
          path: S3R_Production/Debug
          key: ${{ runner.os }}-stm32cubeide-${{ hashFiles('S3R_Production/.project') }}
          restore-keys: |
            ${{ runner.os }}-stm32cubeide-

      - name: Build STM32CubeIde project
        uses: xanderhendriks/action-build-stm32cubeide@v13.0
        with:
          project-path: 'S3R_Production'
