# https://github.com/marketplace/actions/clang-format-lint
name: test-clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './S3R_Production'
        exclude: '*/Drivers */Middlewares */BMP3_SensorAPI'
        extensions: 'h,c'
        clangFormatVersion: 17
        style: file
#    - uses: EndBug/add-and-commit@v9
#      with:
#        author_name: Clang Robot
#        author_email: robot@example.com
#        message: 'Committing clang-format changes'
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}